### ISSUE TITLE
Error shown when launching Vim

### ISSUE THREAD

**Issue by lmartins** [Taverius/vim-colorscheme-manager#1]
Hi, whenever I launch Vim the screen tays blank for a while and then shows:

```
Error detected while processing function colorscheme_manager#init..colorscheme_manager#check_blacklist:
line    1:
E116: Invalid arguments for function index(g:colorscheme_switcher_exclude, a:check_scheme) >= 0 ? 1 : 0 
```

Any tips?

**Comment by punknroll** [comment]
This error is based on a previous error I have:

`
Error detected while processing function "function colorscheme_manager#init..colorscheme_manage
r#check_blacklist":
line    1:
E121: undefined variable: g:colorscheme_switcher_exclude
`

**Comment by punknroll** [comment]
I created a pull request for that:

https://github.com/Taverius/vim-colorscheme-manager/pull/2

**Comment by Taverius** [comment]
Nothing to see here, move along 🙄  😊
