### ISSUE TITLE
does not work at all

### ISSUE THREAD

**Issue by WaterSibilantFalling** [Taverius/vim-colorscheme-manager#3]
SwitchToColorScheme( )   does not exist

So, if this plugin is used,

```
" call xolox#colorscheme_switcher#switch_to(superman)
runtime! autoload/xolox/misc.vim
runtime! autoload/xolox/colorscheme_switcher.vim
runtime! autoload/colorscheme_manager.vim
source /home/me/.vim/autoload/colorscheme_manager.vim

let b:newColorscheme='superman'
call SwitchToColorScheme('superman')
call SwitchToColorScheme(b:newColorscheme)
SwitchToColorScheme('superman')
SwitchToColorScheme(b:newColorscheme)
```

all we get is
line   19:
E117: Unknown function: SwitchToColorScheme
line   20:
E117: Unknown function: SwitchToColorScheme
line   19:
E492: Not an editor command: ^ISwitchToColorScheme('superman')
line   20:
E492: Not an editor command: ^ISwitchToColorScheme(b:newColorscheme)

The only functions are 

function! colorscheme_manager#filename()
function! colorscheme_manager#write()
function! colorscheme_manager#read()
function! colorscheme_manager#check_blacklist(check_scheme)
function! colorscheme_manager#prune_blacklist()
function! colorscheme_manager#add_blacklist(...)
function! colorscheme_manager#rem_blacklist(...)
function! colorscheme_manager#init()

**Comment by Taverius** [comment]
*time passes, empire rise and fall*

Sorry about the ludicrously late reply. I was away from ViM and github.

Regarding the issue, its always worked fine here ... looks like the plugin wasn't installed correctly.

... can I close this?

**Comment by WaterSibilantFalling** [comment]
Sure, I can't remember either.
